---
output: html_document
---

## Preguntas

¡Aquí están las preguntas para la discusión del capítulo 4!

1.  ¿Cuáles son las etapas del modelado de adecuación del hábitat (HSM)?
2.  ¿Qué significa "datos de presencia y datos de ausencia"? ¿Y cuál es su papel en los HSM?
3.  ¿Cuál es el papel de los datos ambientales en los HSM?
4.  ¿Cómo se puede proyectar el nicho cuantificado en el espacio geográfico para obtener la distribución potencial de una especie?
5.  ¿Cómo predecir la ocurrencia de una especie exótica en un nuevo entorno? ¿O de una especie en el pasado o en el futuro?
6.  Nombra tres ejemplos de uso de HSM.

️¡Cualquier duda es sólo escribir al grupo!

## MDS

1 - **¿Cuáles son las etapas del modelado de adecuación del hábitat (HSM)?**

A. Recopilación de datos: las observaciones de campo se recopilan y georreferencian. Las variables ambientales del área se extraen de mapas para cada una de las observaciones.

B. Modelado estadístico: las observaciones de las especies se relacionan con los valores ambientales utilizando enfoques estadísticos para ajustar las curvas de respuesta de las especies a cada predictor ambiental, con el fin de cuantificar el conjunto de condiciones del hábitat (nicho ambiental realizado).

C. Predicciones espaciales: el modelo luego se utiliza para combinar los mapas ambientales iniciales y realizar una proyección espacial en el espacio geográfico, correspondiente a la distribución potencial de la especie.

2 - **¿Qué significa "datos de presencia y datos de ausencia"? ¿Y cuál es su papel en los HSM?**

Hace referencia a la información sobre ocurrencias, es decir, observaciones de la presencia de una especie en una localidad determinada, y la información de ausencia de la misma. Cuando se dispone de esa información (sobre todo de las ausencias conocidas y no solo la presencia) se puede mejorar en gran medida la discriminación entre hábitats adecuados e inadecuados y, por lo tanto, mejorar la cuantificación del nicho. Sin embargo, muchas observaciones de distribuciones de especies utilizadas para calibrar HSM y predecir distribuciones de especies son ocurrencias simples, es decir, observaciones de la presencia de especies sin información de ausencia.

3 - **¿Cuál es el papel de los datos ambientales en los HSM?**

Las variables ambientales o predictores son las que ejercen efectos directos o indirectos sobre las especies, que pueden expresarse como un gradiente que va desde predictores proximales a distales. Existen 3 tipos de influencia que pueden tener sobre las especies: reguladores, disturbios y recursos.

4 - **¿Cómo se puede proyectar el nicho cuantificado en el espacio geográfico para obtener la distribución potencial de una especie?**

Esto se logra aplicando las funciones estadísticas ajustadas al espacio ambiental a cualquier posición del espacio geográfico utilizando sus condiciones ambientales específicas. De esta manera puede asignarse un valor de idoneidad de hábitat a cada celda geográfica.

5 - **¿Cómo predecir la ocurrencia de una especie exótica en un nuevo entorno? ¿O de una especie en el pasado o en el futuro?**

Para predecir la ocurrencia de una especie exótica puede tomarse el modelo que se ajusta en el rango de la especie de interés (en sus condiciones nativas) y luego proyectarlo en todo el mundo o en áreas específicas. En el caso de variaciones temporales, se puede proyectar un modelo a otro período de tiempo y así evaluar el impacto potencial del clima futuro o extrapolarlo a las condiciones pasadas.

6 - **Nombra tres ejemplos de uso de HSM**.

a\. Cuantificar el nicho ambiental de especies y sus cambios en el tiempo y espacio

b\. Prueba de hipótesis evolutivas relacionadas con la biogeografía

c\. Apoyar la planificación de la conservación y la selección de áreas protegidas para una especie
